# Combine Post History, Comments and Answer datasets. Order by Creating Date

In [1]:
import pandas as pd

In [2]:
# 1. Load the CSV files
history_df = pd.read_csv("./data/raw/test/Post_History.csv")
comments_df = pd.read_csv("./data/raw/test/Post_Comments.csv")
answers_df = pd.read_csv("./data/raw/test/Post_Answer.csv")

# 2. Rename ParentId to PostId in answers for consistency
answers_df = answers_df.rename(columns={'ParentId': 'PostId'})

# 3. Add a 'Name' column to indicate the type of each entry
comments_df['Name'] = "Comments"
answers_df['Name'] = "Answers"

# 4. Rename 'Body' to 'Text' in answers to unify text columns
answers_df = answers_df.rename(columns={'Body': 'Text'})

# Add a 'Score' column to history and 
history_df['Score'] = pd.NA

# Reorder all columns to match each other to prepare for concantenate
history_df = history_df[['PostId', 'CreationDate', 'Name', 'Score', 'Text']]
comments_df = comments_df[['PostId', 'CreationDate', 'Name', 'Score', 'Text']]
answers_df = answers_df[['PostId', 'CreationDate', 'Name', 'Score', 'Text']]

# Concatenate all data row wise
combined_df = pd.concat([history_df, comments_df, answers_df], ignore_index=True)

In [3]:
from IPython.display import display
display(combined_df)

,PostId,CreationDate,Name,Score,Text
0,90178,2008-09-18 05:06:17,Initial Title,<NA>,Make a div fill the remaining screen space
1,90178,2008-09-18 05:06:17,Initial Body,<NA>,"I am currently working on a web application, w..."
2,90178,2008-09-18 05:06:17,Initial Tags,<NA>,<table><css><html>
3,90178,2008-09-18 05:29:36,Edit Body,<NA>,"I am currently working on a web application, w..."
4,90178,2008-09-18 07:54:17,Edit Tags,<NA>,<css><table><html>
...,...,...,...,...,...
463,10123953,2021-10-28 12:47:16,Answers,87,"<p>Above answers are all good ðŸ˜Š, here is my im..."
464,10123953,2022-05-04 19:44:44,Answers,6,<p>Here is the shortest way to solve your prob...
465,10123953,2022-10-05 13:22:03,Answers,15,<p>Simple one line solution for me to sort dat...
466,10123953,2023-08-11 11:19:43,Answers,1,<h2>Date form <code>YYYY-MM-DDTHH:mm:ss.sssZ</...
467,10123953,2023-10-27 05:01:19,Answers,5,"<pre><code>var array = [\n {id: 1, date: new ..."

In [ ]:
# Ensure CreationDate is a datetime object and sort by it
combined_df['CreationDate'] = pd.to_datetime(combined_df['CreationDate'])
combined_df = combined_df.sort_values(by=['PostId', 'CreationDate']).reset_index(drop=True)

# Save to CSV (optional)
combined_df.to_csv("./data/raw/test/Combined.csv", index=False)